# ai-generated: 95% - generated by Copilot to run service and DORA tests in Docker Compose
from pathlib import Path

import pytest


class ResultCounter:
    def __init__(self) -> None:
        self.outcomes: dict[str, str] = {}

    def pytest_runtest_logreport(self, report) -> None:
        if report.failed:
            self.outcomes[report.nodeid] = 'failed'
        elif report.when == 'call' and report.passed:
            self.outcomes[report.nodeid] = 'passed'


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    counter = ResultCounter()
    results = pytest.main([
        '-q',
        str(root / 'tests' / 'test_ticket_api.py'),
        str(root / 'tests' / 'test_dora.py'),
        '--maxfail=1',
    ], plugins=[counter])

    passed = sum(outcome == 'passed' for outcome in counter.outcomes.values())
    failed = sum(outcome == 'failed' for outcome in counter.outcomes.values())
    print(f'ITSMLAB-TESTS: passed={passed} failed={failed}')
    return results


if __name__ == '__main__':
    raise SystemExit(main())
