# ai-generated: 90% - generated by Copilot as the Docker Compose pytest runner
import json
import os
import sys
from pathlib import Path

import pytest


SERVICE_URL = os.environ.get('SVCDESK_URL', 'http://svcdesk:8080')


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    results = pytest.main([
        '-q',
        str(root / 'tests' / 'test_ticket_api.py'),
        '--maxfail=1',
    ])

    if results == 0:
        print(f'ITSMLAB-TESTS: passed={10} failed=0')
    return results


if __name__ == '__main__':
    raise SystemExit(main())
